# config_plots.yaml
triangle_comparison:
  enabled: true
  variables: ["pt", "eta", "phi"]
  samples:
    - {tri: 4, color: "blue", label: "Tri 4"}
    - {tri: 8, color: "red", label: "Tri 8"}

calibration_comparison:
  enabled: true
  samples:
    - {label: "Uncalibrated", qty: "raw", color: "black"}
    - {label: "Calibrated", qty: "calibPU200", color: "green"}
